import type { Finding } from "../model/findings";
import {
  APPLE_ID_URL,
  APPLE_LOCATION_SUPPORT,
  APPLE_SIWA_SUPPORT,
  GOOGLE_ACTIVITY_URL,
  GOOGLE_PERMISSIONS_URL,
  GOOGLE_SECURITY_URL,
  MICROSOFT_PERMISSIONS,
  OPENAI_ACCOUNT,
  ANTHROPIC_ACCOUNT,
} from "../model/findings";

export type SampleMessage = {
  id: string;
  subject: string;
  from: string;
  date: string;
  snippet: string;
  body: string;
};

/**
 * Multi-surface demo map — Access / Agents / Location balanced.
 * Not Google/Gmail-heavy. howKnown: demo for all.
 */
export const DEMO_FINDINGS: Finding[] = [
  // —— Access (Google + Apple + Microsoft + app) ——
  {
    id: "demo-access-google-notion",
    kind: "oauth_grant",
    title: "Notion granted access to Google Account",
    party: "Notion",
    summary: "OAuth grant on Google. Review scopes; revoke if unused.",
    evidenceDate: "2024-11-03",
    source: "demo",
    howKnown: "demo",
    ecosystem: "google",
    confidence: "high",
    revokeUrl: GOOGLE_PERMISSIONS_URL,
  },
  {
    id: "demo-access-apple-siwa-notion",
    kind: "connected_app",
    title: "Sign in with Apple → Notion",
    party: "Notion",
    summary:
      "Apple ID used to sign into Notion. Manage SIWA apps at appleid.apple.com — Umbra cannot read SIWA list from the web.",
    evidenceDate: "2024-06-12",
    source: "demo",
    howKnown: "demo",
    ecosystem: "apple",
    confidence: "medium",
    revokeUrl: APPLE_SIWA_SUPPORT,
  },
  {
    id: "demo-access-apple-siwa-slack",
    kind: "connected_app",
    title: "Sign in with Apple → Slack",
    party: "Slack",
    summary: "Workspace sign-in via Apple. Confirm you still use this workspace.",
    evidenceDate: "2023-09-01",
    source: "demo",
    howKnown: "demo",
    ecosystem: "apple",
    confidence: "medium",
    revokeUrl: APPLE_ID_URL,
  },
  {
    id: "demo-access-ms-todo",
    kind: "oauth_grant",
    title: "Microsoft account: third-party app consent",
    party: "Todoist",
    summary:
      "Microsoft account permissions / consent. Review at account.live.com — not a Gmail signal.",
    evidenceDate: "2024-02-20",
    source: "demo",
    howKnown: "demo",
    ecosystem: "microsoft",
    confidence: "medium",
    revokeUrl: MICROSOFT_PERMISSIONS,
  },
  {
    id: "demo-access-google-zoom",
    kind: "connected_app",
    title: "Zoom connected (Google calendar class)",
    party: "Zoom",
    summary: "Calendar-style integration on Google stack. Revoke if unused.",
    evidenceDate: "2024-01-22",
    source: "demo",
    howKnown: "demo",
    ecosystem: "google",
    confidence: "medium",
    revokeUrl: GOOGLE_PERMISSIONS_URL,
  },
  {
    id: "demo-access-browser-ext",
    kind: "other_access",
    title: "Browser extension with account access",
    party: "Password manager extension",
    summary:
      "Browser-level principal with standing access to sites. Review extension permissions in the browser.",
    evidenceDate: "2025-01-10",
    source: "demo",
    howKnown: "demo",
    ecosystem: "browser",
    confidence: "low",
    revokeUrl: "https://support.google.com/chrome_webstore/answer/2664769",
  },

  // —— Agents (≥5 distinct) ——
  {
    id: "demo-agent-openai",
    kind: "ai_agent",
    title: "ChatGPT / OpenAI connectors",
    party: "ChatGPT",
    summary:
      "AI product with mail/files-class connectors. Inventory only — open OpenAI settings to manage.",
    evidenceDate: "2025-03-14",
    source: "demo",
    howKnown: "demo",
    ecosystem: "ai",
    confidence: "high",
    revokeUrl: OPENAI_ACCOUNT,
    accessTags: ["mail", "files", "browser"],
  },
  {
    id: "demo-agent-claude",
    kind: "ai_agent",
    title: "Claude / Anthropic projects access",
    party: "Claude",
    summary: "Assistant with project/file context. Audit connectors in Claude settings.",
    evidenceDate: "2025-06-01",
    source: "demo",
    howKnown: "demo",
    ecosystem: "ai",
    confidence: "high",
    revokeUrl: ANTHROPIC_ACCOUNT,
    accessTags: ["files", "mail"],
  },
  {
    id: "demo-agent-cursor",
    kind: "ai_agent",
    title: "Cursor IDE coding agent",
    party: "Cursor",
    summary: "Dev agent with repo/filesystem reach. Review account link and workspace trust.",
    evidenceDate: "2025-10-01",
    source: "demo",
    howKnown: "demo",
    ecosystem: "ai",
    confidence: "medium",
    revokeUrl: "https://www.cursor.com/",
    accessTags: ["files", "other"],
  },
  {
    id: "demo-agent-browser",
    kind: "ai_agent",
    title: "Browser AI agent / side-panel assistant",
    party: "Browser agent",
    summary:
      "Agent that can see tabs or act in-page. Review browser extension + site access.",
    evidenceDate: "2025-09-12",
    source: "demo",
    howKnown: "demo",
    ecosystem: "browser",
    confidence: "medium",
    revokeUrl: "https://support.google.com/chrome_webstore/answer/2664769",
    accessTags: ["browser", "other"],
  },
  {
    id: "demo-agent-home",
    kind: "ai_agent",
    title: "Home automation / IFTTT-style agent",
    party: "Home automations",
    summary:
      "Automation principal with device and location-adjacent triggers. Review applets and OAuth.",
    evidenceDate: "2022-09-01",
    source: "demo",
    howKnown: "demo",
    ecosystem: "other",
    confidence: "medium",
    revokeUrl: GOOGLE_PERMISSIONS_URL,
    accessTags: ["location", "calendar", "other"],
  },
  {
    id: "demo-agent-copilot",
    kind: "ai_agent",
    title: "Microsoft Copilot productivity agent",
    party: "Copilot",
    summary: "Assistant on Microsoft stack. Review Microsoft account consents.",
    evidenceDate: "2025-08-02",
    source: "demo",
    howKnown: "demo",
    ecosystem: "microsoft",
    confidence: "medium",
    revokeUrl: MICROSOFT_PERMISSIONS,
    accessTags: ["mail", "files", "calendar"],
  },

  // —— Location (≥4 across Apple + Google + app) ——
  {
    id: "demo-loc-apple-always",
    kind: "location",
    title: "iOS/macOS: Location set to Always (example app)",
    party: "Weather / maps-class app",
    summary:
      "Always location is high-risk standing access. Change in Settings → Privacy → Location. Web app cannot read TCC.",
    evidenceDate: "2025-04-01",
    source: "demo",
    howKnown: "demo",
    ecosystem: "apple",
    confidence: "medium",
    revokeUrl: APPLE_LOCATION_SUPPORT,
  },
  {
    id: "demo-loc-apple-significant",
    kind: "location",
    title: "Significant Locations / System Services",
    party: "Apple System Services",
    summary:
      "System location history class. Review on device under Location Services → System Services.",
    evidenceDate: "2024-11-20",
    source: "demo",
    howKnown: "demo",
    ecosystem: "device",
    confidence: "low",
    revokeUrl: APPLE_LOCATION_SUPPORT,
  },
  {
    id: "demo-loc-google-timeline",
    kind: "location",
    title: "Google Location History / timeline",
    party: "Google Maps",
    summary: "Timeline / activity controls — not the same as third-party OAuth.",
    evidenceDate: "2024-05-11",
    source: "demo",
    howKnown: "demo",
    ecosystem: "google",
    confidence: "medium",
    revokeUrl: GOOGLE_ACTIVITY_URL,
  },
  {
    id: "demo-loc-app-geofence",
    kind: "location",
    title: "App geofence / “notify when I arrive”",
    party: "Home / shopping app",
    summary:
      "Geofence automation uses location in background. Review app location mode (While Using vs Always).",
    evidenceDate: "2024-08-08",
    source: "demo",
    howKnown: "demo",
    ecosystem: "device",
    confidence: "medium",
    revokeUrl: APPLE_LOCATION_SUPPORT,
  },
  {
    id: "demo-loc-ride",
    kind: "location",
    title: "Ride app background location",
    party: "Uber",
    summary: "Trip apps often keep location. Disable background if idle.",
    evidenceDate: "2023-12-09",
    source: "demo",
    howKnown: "demo",
    ecosystem: "other",
    confidence: "low",
    revokeUrl: GOOGLE_PERMISSIONS_URL,
  },

  // —— Alerts (light, multi-ecosystem) ——
  {
    id: "demo-sec-google",
    kind: "security_alert",
    title: "Google: new sign-in alert (example)",
    party: "Google Account",
    summary: "Session alert class. Confirm devices if real.",
    evidenceDate: "2025-11-20",
    source: "demo",
    howKnown: "demo",
    ecosystem: "google",
    confidence: "high",
    revokeUrl: GOOGLE_SECURITY_URL,
  },
  {
    id: "demo-sec-apple",
    kind: "security_alert",
    title: "Apple ID: new device or sign-in (example)",
    party: "Apple ID",
    summary: "Review devices at appleid.apple.com. Demo only.",
    evidenceDate: "2025-07-15",
    source: "demo",
    howKnown: "demo",
    ecosystem: "apple",
    confidence: "medium",
    revokeUrl: APPLE_ID_URL,
  },
];

/** Sample Gmail-like messages for optional archaeology parsers (secondary). */
export const SAMPLE_MESSAGES: SampleMessage[] = [
  {
    id: "msg-1",
    subject: "Security alert: Notion was granted access to your Google Account",
    from: "Google <no-reply@accounts.google.com>",
    date: "2024-11-03",
    snippet: "Notion was granted access to your Google Account",
    body: "Notion was granted access to your Google Account. Review third-party access.",
  },
  {
    id: "msg-2",
    subject: "OpenAI: app connected to your Google Account",
    from: "Google <no-reply@accounts.google.com>",
    date: "2025-03-14",
    snippet: "OpenAI ChatGPT connected",
    body: "ChatGPT connected to your Google Account with access to some of your data.",
  },
  {
    id: "msg-3",
    subject: "Security alert: New sign-in on Windows",
    from: "Google <no-reply@accounts.google.com>",
    date: "2025-11-20",
    snippet: "New sign-in on Windows device",
    body: "Your Google Account was just signed in on a Windows device.",
  },
  {
    id: "msg-4",
    subject: "Location sharing update for your account",
    from: "Google Maps <maps-noreply@google.com>",
    date: "2024-05-11",
    snippet: "Someone can see your location",
    body: "Location sharing is on. Review who can see your real-time location.",
  },
  {
    id: "msg-5",
    subject: "IFTTT is connected to your Google Account",
    from: "Google <no-reply@accounts.google.com>",
    date: "2022-09-01",
    snippet: "IFTTT connected",
    body: "IFTTT is connected to your Google Account.",
  },
  {
    id: "msg-6",
    subject: "GitHub: new OAuth application authorized",
    from: "GitHub <noreply@github.com>",
    date: "2024-02-10",
    snippet: "OAuth application authorized",
    body: "A third-party application was authorized via OAuth.",
  },
  {
    id: "msg-7",
    subject: "Your Uber account location settings",
    from: "Uber <no-reply@uber.com>",
    date: "2023-12-09",
    snippet: "Location access helps pickups",
    body: "We use your device location for pickups.",
  },
  {
    id: "msg-8",
    subject: "Slack: Sign in with Google completed",
    from: "Slack <feedback@slack.com>",
    date: "2023-06-18",
    snippet: "Signed in with Google",
    body: "You signed in to Slack using Sign in with Google.",
  },
  {
    id: "msg-9",
    subject: "Dropbox was granted access to your Google Account",
    from: "Google <no-reply@accounts.google.com>",
    date: "2023-02-14",
    snippet: "Dropbox was granted access",
    body: "Dropbox was granted access to your Google Account.",
  },
  {
    id: "msg-10",
    subject: "Anthropic Claude connected via Google",
    from: "Google <no-reply@accounts.google.com>",
    date: "2025-06-01",
    snippet: "Claude AI assistant app connected",
    body: "Claude by Anthropic was connected as an AI assistant with limited data access.",
  },
  {
    id: "msg-11",
    subject: "Security alert: App password created",
    from: "Google <no-reply@accounts.google.com>",
    date: "2021-04-30",
    snippet: "A new app password was created",
    body: "A new app password was created for your Google Account.",
  },
  {
    id: "msg-12",
    subject: "Find My Device: location of your phone",
    from: "Google <no-reply@accounts.google.com>",
    date: "2024-08-19",
    snippet: "Device location available",
    body: "Find My Device can show the device location of your phone.",
  },
  {
    id: "msg-13",
    subject: "Cursor IDE: Google account linked for agent features",
    from: "Cursor <hello@cursor.com>",
    date: "2025-10-01",
    snippet: "AI coding agent linked",
    body: "Your Google account is linked so Cursor AI agent features can sync.",
  },
];
